name: Java CI with Gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build jacocoTestCoverageVerification

  tests:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3.2.0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Tests
      run: ./gradlew clean test --info "-Dselenide.headless=true"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: tests_Report_index.html
        path: build/reports/tests/test/
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: jococo_Report_index.html
        path: build/jacocoHtml/
  report:
    runs-on: ubuntu-latest
    needs: tests 
    if: ${{ always() }} 
    steps:
    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: tests_Report_index.html
    - name: Download Test Reports Folder
      uses: actions/download-artifact@v2
      with:
        name: jococo_Report_index.html
